OPENAI_API_KEY="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"
LANGCHAIN_TRACING_V2 = true
LANGCHAIN_ENDPOINT = "https://api.smith.langchain.com"
LANGCHAIN_API_KEY = "ls__da081afeffe1473a8e3b1d0b1da4b45c"
HUGGINGFACEHUB_API_TOKEN = "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"
GOOGLE_CSE_ID = "b399136301a3e47b3"
GOOGLE_API_KEY = "AIzaSyAQA6Nmsj369mdeRlzaXDuFgv15wJVc6J8"
ALPHA_VANTAGE_API_KEY = NKQEC5JH0JPK68VF